[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
allow_internal_expect_revert = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
